name: Davis Song
title: Davis | A blog
description: A blog for Davis Song
tags:
  - blog
  - Davis Song
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: davis@davissong.com
disqus_username: disqus_username
